### ISSUE TITLE
[Bug]: incompatibility with Survivality

### ISSUE THREAD

**Issue by 800020h** [Fuzss/leavesbegone#3]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

4.0.1

### Notes (Required)

normal leaves don't decay faster
Terrestrias's distance: 14 leaves still work though

possibly the same as https://github.com/Fuzss/leavesbegone/issues/1

Survivality (I was using 1.1.1)
https://modrinth.com/mod/survivality

**Comment by Fuzss** [comment]
Yep, that's the same issue. They have the exact same code as that other mod from #1 .

**Comment by Fuzss** [comment]
I added the incompatibility to `fabric.mod.json` for 1.19.3+ so that people will be notified when both mods are installed and can remove either one.
