### ISSUE TITLE
[Bug]: Server hangs after "Dispatching unloading event for config leavesbegone-server.toml"

### ISSUE THREAD

**Issue by HoldYourWaffle** [Fuzss/leavesbegone#7]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.21

### Mod Version(s) (Required)

v21.0.0

### Minimal Setup (Required)

Yes

### Notes (Required)

**Current behavior:** Leaves Be Gone seems to prevent a dedicated server from closing down properly.

**Steps to reproduce:**
1. Start a dedicated server with Leaves Be Gone and its dependencies.
2. `stop` the server.
3. Observe that the process seems to hang after the "Dispatching unloading event for config leavesbegone-server.toml" message.

I've seen similar behavior when the server crashes.

### latest.log (Required)

https://gist.github.com/HoldYourWaffle/36deca828916b8f3e53f78e81b1078c4

**Comment by Fuzss** [comment]
https://github.com/Fuzss/forgeconfigapiport/issues/68
