### ISSUE TITLE
[Suggestion]: Serverside variant without Puzzle Lib

### ISSUE THREAD

**Issue by Wizqok** [Fuzss/leavesbegone#8]
### Mod Loader (Optional)

NeoForge

### Minecraft Version(s) (Optional)

1.21.1

### Suggestion (Required)

Just want to ask if a simple serverside version would be reasonable, as puzzle lib has to be installed at server & client afai experienced, as clients cant connect without puzzle lib.

Thanks for the great mod though
br

**Comment by Fuzss** [comment]
Please share screenshot of the message you get when trying to connect a vanilla client to a server with LBG + Puzzles Lib.

**Comment by Wizqok** [comment]
![{BCCF3416-1F52-4331-ACE3-5E34CDBBC33F}](https://github.com/user-attachments/assets/77ed0971-436d-41a3-8a5a-9fd72ed68412)

**Comment by Fuzss** [comment]
Ah in that case please also the latest.log

**Comment by Wizqok** [comment]
already looked into it but nothing to show, only one entry "invalid player data and disconnect" from renderthread like shown on the screen, thats it

**Comment by Fuzss** [comment]
The server log should have the information

**Comment by Wizqok** [comment]
[[185139] [Server threadERROR] [ne.n.txt](https://github.com/user-attachments/files/17191096/185139.Server.threadERROR.ne.n.txt)

hope that helps

**Comment by Fuzss** [comment]
Alright, thank you! All this should work now in Puzzles Lib v21.1.17.
